baseURL = "https://yogaandoffice.netlify.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Yoga & Office"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Inicio"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "about"
name = "Acerca"
weight = 1
[[menu.footer]]
URL = "project"
name = "Servicios"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contacto"
weight = 6
[[menu.main]]
URL = "about"
name = "Acerca"
weight = 1
[[menu.main]]
URL = "project"
name = "Servicios"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contacto"
weight = 6
[params]
author = "Themefisher"
contact_form_action = "https://formspree.io/mwkndryw"
description = "This is meta description"
email = "anacehuhe@gmail.com"
google_analitycs_id = ""
location = "Barcelona, Catalunya"
logo = "images/logo.png"
multi_author = false
phone = "638283233"
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Precios"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "http://linkedin.com/in/anaceciliahurtado"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/officeandyoga/"
[[params.social]]
icon = "ion-social-telegram-outline"
link = " https://t.me/@yogaandoffice"
